export const DRIVER_STATES = {
  REGISTERED: 'REGISTERED',
  DOCUMENTS_SUBMITTED: 'DOCUMENTS_SUBMITTED',
  DOCUMENT_VERIFICATION_PENDING: 'DOCUMENT_VERIFICATION_PENDING',
  ADDRESS_VERIFICATION_PENDING: 'ADDRESS_VERIFICATION_PENDING',
  APPROVED: 'APPROVED',
  APPROVED_BIKE_NOT_ASSIGNED: 'APPROVED_BIKE_NOT_ASSIGNED',
  BIKE_ASSIGNED: 'BIKE_ASSIGNED',
  BIKE_HANDOVER_PENDING: 'BIKE_HANDOVER_PENDING',
  ACTIVE_DRIVER: 'ACTIVE_DRIVER',
  SUSPENDED: 'SUSPENDED',
  REJECTED: 'REJECTED',
  ACCOUNT_CLOSED: 'ACCOUNT_CLOSED'
};

export const BREAK_TYPES = {
  PLANNED: 'Planned Break (1 Hour Max)',
  SHORT: 'Short Break (15 Mins)',
  EMERGENCY: 'Emergency Break'
};

export const MAX_DAILY_DUTY_HOURS = 12;
export const SPEED_LIMIT_KMH = 60;
export const IDLE_LIMIT_MINUTES = 30;
